# Generated by Django 5.0.7 on 2024-07-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='number_of_vacant',
            new_name='number_of_female_tenant',
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_male_tenant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
