# Generated by Django 5.0.6 on 2024-06-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='number_of_slots',
            new_name='number_of_vacant',
        ),
        migrations.AddField(
            model_name='property',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
