# Generated by Django 5.0.6 on 2024-06-06 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_rent_alter_property_rent_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_address', to='property.address'),
        ),
    ]
