# Generated by Django 5.0.6 on 2024-06-09 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_address_id_alter_coordinates_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='coordinates',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinates_address', to='property.address'),
        ),
    ]
