# Generated by Django 5.0.6 on 2024-07-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_remove_coordinates_address_property_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, default='Philippines', max_length=1000, null=True),
        ),
    ]
