# Generated by Django 5.0.6 on 2024-07-07 12:51

import django.db.models.deletion
import utils.helpers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.CharField(default=utils.helpers.generate_custom_id, editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='feed_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_content', to='property.property')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedFeed',
            fields=[
                ('id', models.CharField(default=utils.helpers.generate_custom_id, editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savedfeed_content', to='feed.feed')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savedfeed_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
