# Generated by Django 5.0.6 on 2024-06-09 09:25

import feed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='id',
            field=models.CharField(default=feed.models.generate_custom_id, editable=False, max_length=17, primary_key=True, serialize=False, unique=True),
        ),
    ]
