# Generated by Django 5.0.6 on 2024-06-14 14:40

import django.db.models.deletion
import functions.generate_custom_id
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_feed_id'),
        ('property', '0008_remove_coordinates_address_property_coordinates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFeed',
            fields=[
                ('id', models.CharField(default=functions.generate_custom_id.generate_custom_id, editable=False, max_length=17, primary_key=True, serialize=False, unique=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savedfeed_content', to='property.property')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savedfeed_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
