# Generated by Django 5.0.6 on 2024-06-14 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_savedfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfeed',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savedfeed_content', to='feed.feed'),
        ),
    ]
