# Generated by Django 5.0.6 on 2024-06-09 09:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
