# Generated by Django 5.0.6 on 2024-06-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_alter_message_id_alter_notification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
