# Generated by Django 5.0.6 on 2024-07-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
